version: "3"
services:
  database:
    image: postgres:9.6.6
    volumes:
      - database:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
        - 5432:5432

volumes:
    database:
      external: false
